// <auto-generated />
using EnglishLearningAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishLearningAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("EnglishLearningAPI.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Lessons")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Students")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#10b981",
                            Description = "Build your basics with essential grammar, common phrases, and everyday vocabulary.",
                            Duration = "8 weeks",
                            Emoji = "🌱",
                            Lessons = 24,
                            Level = "Beginner",
                            Students = "3.2K",
                            Title = "English Foundations"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#3b82f6",
                            Description = "Master daily conversations, shopping, travel, and social interactions with confidence.",
                            Duration = "10 weeks",
                            Emoji = "📚",
                            Lessons = 30,
                            Level = "Elementary",
                            Students = "2.8K",
                            Title = "Everyday English"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#8b5cf6",
                            Description = "Perfect your professional communication: emails, meetings, presentations, and negotiations.",
                            Duration = "10 weeks",
                            Emoji = "💼",
                            Lessons = 28,
                            Level = "Intermediate",
                            Students = "1.9K",
                            Title = "Business English"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#f59e0b",
                            Description = "Sharpen your ears with podcasts, news, movies, and real-world audio from native speakers.",
                            Duration = "12 weeks",
                            Emoji = "🎧",
                            Lessons = 36,
                            Level = "All Levels",
                            Students = "2.5K",
                            Title = "Listening Mastery"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#ef4444",
                            Description = "Overcome speaking anxiety with guided practice, role-plays, and AI pronunciation coaching.",
                            Duration = "8 weeks",
                            Emoji = "🗣️",
                            Lessons = 20,
                            Level = "Intermediate",
                            Students = "1.6K",
                            Title = "Speaking Confidence"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#ec4899",
                            Description = "Comprehensive IELTS prep covering all four skills: Listening, Reading, Writing, and Speaking.",
                            Duration = "14 weeks",
                            Emoji = "🏆",
                            Lessons = 40,
                            Level = "Advanced",
                            Students = "4.1K",
                            Title = "IELTS Preparation"
                        });
                });

            modelBuilder.Entity("EnglishLearningAPI.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Options");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = 1,
                            OptionsJson = "[\"Very rare\",\"Found everywhere\",\"Extremely loud\",\"Very old\"]",
                            Question = "What is the meaning of 'ubiquitous'?"
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = 1,
                            OptionsJson = "[\"abandoned\",\"accomplished\",\"avoided\",\"accused\"]",
                            Question = "Choose the correct word: 'She _____ her goal after years of hard work.'"
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswer = 1,
                            OptionsJson = "[\"Malevolent\",\"Benevolent\",\"Diligent\",\"Resilient\"]",
                            Question = "Which word means 'kind and generous'?"
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswer = 1,
                            OptionsJson = "[\"A type of music\",\"Finding good things by chance\",\"A feeling of sadness\",\"An ancient language\"]",
                            Question = "'Serendipity' refers to:"
                        },
                        new
                        {
                            Id = 5,
                            CorrectAnswer = 1,
                            OptionsJson = "[\"Give up easily\",\"Continue despite difficulties\",\"Celebrate success\",\"Feel confused\"]",
                            Question = "What does 'persevere' mean?"
                        });
                });

            modelBuilder.Entity("EnglishLearningAPI.Models.Vocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phonetic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vocabularies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Action",
                            Example = "She accomplished her goal of running a marathon.",
                            Meaning = "To finish something successfully",
                            Phonetic = "/əˈkɑːm.plɪʃ/",
                            Word = "Accomplish"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Adjective",
                            Example = "The benevolent donor funded the school.",
                            Meaning = "Kind and generous",
                            Phonetic = "/bəˈnev.əl.ənt/",
                            Word = "Benevolent"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Adjective",
                            Example = "She was diligent in her studies.",
                            Meaning = "Careful and persistent in work",
                            Phonetic = "/ˈdɪl.ɪ.dʒənt/",
                            Word = "Diligent"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Adjective",
                            Example = "He gave an eloquent speech at the ceremony.",
                            Meaning = "Fluent and persuasive in speaking",
                            Phonetic = "/ˈel.ə.kwənt/",
                            Word = "Eloquent"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Action",
                            Example = "The business began to flourish after the rebrand.",
                            Meaning = "To grow or develop successfully",
                            Phonetic = "/ˈflɜː.rɪʃ/",
                            Word = "Flourish"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Adjective",
                            Example = "He is meticulous about his work.",
                            Meaning = "Showing great attention to detail",
                            Phonetic = "/məˈtɪk.jə.ləs/",
                            Word = "Meticulous"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Action",
                            Example = "She persevered through many challenges.",
                            Meaning = "To continue despite difficulties",
                            Phonetic = "/ˌpɜː.sɪˈvɪr/",
                            Word = "Persevere"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Adjective",
                            Example = "Children are often more resilient than adults.",
                            Meaning = "Able to recover quickly from difficulties",
                            Phonetic = "/rɪˈzɪl.i.ənt/",
                            Word = "Resilient"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Noun",
                            Example = "It was pure serendipity that they met.",
                            Meaning = "Finding good things by chance",
                            Phonetic = "/ˌser.ənˈdɪp.ə.ti/",
                            Word = "Serendipity"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Adjective",
                            Example = "Smartphones have become ubiquitous.",
                            Meaning = "Found everywhere",
                            Phonetic = "/juːˈbɪk.wɪ.təs/",
                            Word = "Ubiquitous"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Action",
                            Example = "Companies that innovate tend to succeed.",
                            Meaning = "To introduce new methods or ideas",
                            Phonetic = "/ˈɪn.ə.veɪt/",
                            Word = "Innovate"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Adjective",
                            Example = "We need a pragmatic approach to this problem.",
                            Meaning = "Dealing with things practically",
                            Phonetic = "/præɡˈmæt.ɪk/",
                            Word = "Pragmatic"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
